language: java
sudo: false
install: true
jdk: 
  - openjdk8
  - openjdk11
env:
  - MAVEN_OPTS="-Dhttps.protocol=TLSv1.2"
script: mvn install -Prelease -Dgpg.skip=true -Djdk.enforced=1.7
after_success: mvn verify -Pcoveralls
